/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class ComponentMetaDataCollectionSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ComponentMetaDataCollectionSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ComponentMetaDataCollectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_ComponentMetaDataCollectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ComponentMetaDataSwig getByKey(byte key) {
    long cPtr = DeviceDetectionHashEngineModuleJNI.ComponentMetaDataCollectionSwig_getByKey(swigCPtr, this, (int)key);
    return (cPtr == 0) ? null : new ComponentMetaDataSwig(cPtr, true);
  }

  public ComponentMetaDataSwig getByIndex(long index) {
    long cPtr = DeviceDetectionHashEngineModuleJNI.ComponentMetaDataCollectionSwig_getByIndex(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ComponentMetaDataSwig(cPtr, true);
  }

  public long getSize() {
    return DeviceDetectionHashEngineModuleJNI.ComponentMetaDataCollectionSwig_getSize(swigCPtr, this);
  }

}
