/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class ConfigDeviceDetectionSwig extends ConfigBaseSwig {
  private transient long swigCPtr;

  protected ConfigDeviceDetectionSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigDeviceDetectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_ConfigDeviceDetectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setUpdateMatchedUserAgent(boolean update) {
    DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_setUpdateMatchedUserAgent(swigCPtr, this, update);
  }

  public void setMaxMatchedUserAgentLength(int length) {
    DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_setMaxMatchedUserAgentLength(swigCPtr, this, length);
  }

  public void setAllowUnmatched(boolean allow) {
    DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_setAllowUnmatched(swigCPtr, this, allow);
  }

  public boolean getUpdateMatchedUserAgent() {
    return DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_getUpdateMatchedUserAgent(swigCPtr, this);
  }

  public int getMaxMatchedUserAgentLength() {
    return DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_getMaxMatchedUserAgentLength(swigCPtr, this);
  }

  public boolean getAllowUnmatched() {
    return DeviceDetectionHashEngineModuleJNI.ConfigDeviceDetectionSwig_getAllowUnmatched(swigCPtr, this);
  }

}
