/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class DoubleValueSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DoubleValueSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DoubleValueSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_DoubleValueSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DoubleValueSwig() {
    this(DeviceDetectionHashEngineModuleJNI.new_DoubleValueSwig(), true);
  }

  public boolean hasValue() {
    return DeviceDetectionHashEngineModuleJNI.DoubleValueSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return DeviceDetectionHashEngineModuleJNI.DoubleValueSwig_getNoValueMessage(swigCPtr, this);
  }

  public double getValue() {
    return DeviceDetectionHashEngineModuleJNI.DoubleValueSwig_getValue(swigCPtr, this);
  }

}
