/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class EngineBaseSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EngineBaseSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineBaseSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_EngineBaseSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public void setLicenseKey(String licenceKey) {
    DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_setLicenseKey(swigCPtr, this, licenceKey);
  }

  public void setDataUpdateUrl(String updateUrl) {
    DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_setDataUpdateUrl(swigCPtr, this, updateUrl);
  }

  public MetaDataSwig getMetaData() {
    long cPtr = DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getMetaData(swigCPtr, this);
    return (cPtr == 0) ? null : new MetaDataSwig(cPtr, false);
  }

  public boolean getAutomaticUpdatesEnabled() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getAutomaticUpdatesEnabled(swigCPtr, this);
  }

  public ResultsBaseSwig processBase(EvidenceBaseSwig evidence) {
    long cPtr = DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_processBase(swigCPtr, this, EvidenceBaseSwig.getCPtr(evidence), evidence);
    return (cPtr == 0) ? null : new ResultsBaseSwig(cPtr, true);
  }

  public void refreshData() {
    DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_refreshData__SWIG_0(swigCPtr, this);
  }

  public void refreshData(String fileName) {
    DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_refreshData__SWIG_1(swigCPtr, this, fileName);
  }

  public void refreshData(byte[] data) {
    DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_refreshData__SWIG_2(swigCPtr, this, data);
  }

  public String getDataUpdateUrl() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getDataUpdateUrl(swigCPtr, this);
  }

  public Date getPublishedTime() {
    return new Date(DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getPublishedTime(swigCPtr, this), true);
  }

  public Date getUpdateAvailableTime() {
    return new Date(DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getUpdateAvailableTime(swigCPtr, this), true);
  }

  public String getDataFilePath() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getDataFilePath(swigCPtr, this);
  }

  public String getDataFileTempPath() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getDataFileTempPath(swigCPtr, this);
  }

  public String getProduct() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getProduct(swigCPtr, this);
  }

  public String getType() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getType(swigCPtr, this);
  }

  public VectorStringSwig getKeys() {
    long cPtr = DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getKeys(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorStringSwig(cPtr, false);
  }

  public boolean getIsThreadSafe() {
    return DeviceDetectionHashEngineModuleJNI.EngineBaseSwig_getIsThreadSafe(swigCPtr, this);
  }

}
