/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class EvidenceBaseSwig extends MapStringStringSwig implements AutoCloseable {
  private transient long swigCPtr;

  protected EvidenceBaseSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionHashEngineModuleJNI.EvidenceBaseSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EvidenceBaseSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_EvidenceBaseSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
    this.delete();
  }

  public EvidenceBaseSwig() {
    this(DeviceDetectionHashEngineModuleJNI.new_EvidenceBaseSwig(), true);
  }

  public void addFromBytes(byte[] key, byte[] value) {
    DeviceDetectionHashEngineModule.Evidence_AddFromBytes(this, key, value);
  }

}
