/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class ProfileMetaDataCollectionSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProfileMetaDataCollectionSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileMetaDataCollectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_ProfileMetaDataCollectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public ProfileMetaDataSwig getByKey(long key) {
    long cPtr = DeviceDetectionHashEngineModuleJNI.ProfileMetaDataCollectionSwig_getByKey(swigCPtr, this, key);
    return (cPtr == 0) ? null : new ProfileMetaDataSwig(cPtr, true);
  }

  public ProfileMetaDataSwig getByIndex(long index) {
    long cPtr = DeviceDetectionHashEngineModuleJNI.ProfileMetaDataCollectionSwig_getByIndex(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ProfileMetaDataSwig(cPtr, true);
  }

  public long getSize() {
    return DeviceDetectionHashEngineModuleJNI.ProfileMetaDataCollectionSwig_getSize(swigCPtr, this);
  }

}
