/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class RequiredPropertiesConfigSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RequiredPropertiesConfigSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RequiredPropertiesConfigSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_RequiredPropertiesConfigSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RequiredPropertiesConfigSwig() {
    this(DeviceDetectionHashEngineModuleJNI.new_RequiredPropertiesConfigSwig__SWIG_0(), true);
  }

  public RequiredPropertiesConfigSwig(VectorStringSwig properties) {
    this(DeviceDetectionHashEngineModuleJNI.new_RequiredPropertiesConfigSwig__SWIG_1(VectorStringSwig.getCPtr(properties), properties), true);
  }

  public RequiredPropertiesConfigSwig(String properties) {
    this(DeviceDetectionHashEngineModuleJNI.new_RequiredPropertiesConfigSwig__SWIG_2(properties), true);
  }

  public VectorStringSwig getProperties() {
    return new VectorStringSwig(DeviceDetectionHashEngineModuleJNI.RequiredPropertiesConfigSwig_getProperties(swigCPtr, this), true);
  }

}
