/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class ResultsDeviceDetectionSwig extends ResultsBaseSwig {
  private transient long swigCPtr;

  protected ResultsDeviceDetectionSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionHashEngineModuleJNI.ResultsDeviceDetectionSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultsDeviceDetectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_ResultsDeviceDetectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getDeviceId() {
    return DeviceDetectionHashEngineModuleJNI.ResultsDeviceDetectionSwig_getDeviceId(swigCPtr, this);
  }

  public String getUserAgent(long resultIndex) {
    return DeviceDetectionHashEngineModuleJNI.ResultsDeviceDetectionSwig_getUserAgent(swigCPtr, this, resultIndex);
  }

  public int getUserAgents() {
    return DeviceDetectionHashEngineModuleJNI.ResultsDeviceDetectionSwig_getUserAgents(swigCPtr, this);
  }

}
