/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class ResultsHashSwig extends ResultsDeviceDetectionSwig {
  private transient long swigCPtr;

  protected ResultsHashSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultsHashSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_ResultsHashSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getDeviceId() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getDeviceId(swigCPtr, this);
  }

  public int getRank() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getRank(swigCPtr, this);
  }

  public int getDifference() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getDifference(swigCPtr, this);
  }

  public int getDrift() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getDrift(swigCPtr, this);
  }

  public int getIterations() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getIterations(swigCPtr, this);
  }

  public int getMethod() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getMethod(swigCPtr, this);
  }

  public int getMatchedNodes() {
    return DeviceDetectionHashEngineModuleJNI.ResultsHashSwig_getMatchedNodes(swigCPtr, this);
  }

}
