/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.hash.engine.onpremise.interop.swig;

public class VectorStringValuesSwig implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorStringValuesSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStringValuesSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionHashEngineModuleJNI.delete_VectorStringValuesSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    this.delete();
  }

  public VectorStringValuesSwig() {
    this(DeviceDetectionHashEngineModuleJNI.new_VectorStringValuesSwig(), true);
  }

  public boolean hasValue() {
    return DeviceDetectionHashEngineModuleJNI.VectorStringValuesSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return DeviceDetectionHashEngineModuleJNI.VectorStringValuesSwig_getNoValueMessage(swigCPtr, this);
  }

  public VectorStringSwig getValue() {
    return new VectorStringSwig(DeviceDetectionHashEngineModuleJNI.VectorStringValuesSwig_getValue(swigCPtr, this), true);
  }

}
