/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class BoolValueSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BoolValueSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoolValueSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_BoolValueSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoolValueSwig() {
    this(DeviceDetectionPatternEngineModuleJNI.new_BoolValueSwig(), true);
  }

  public boolean hasValue() {
    return DeviceDetectionPatternEngineModuleJNI.BoolValueSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return DeviceDetectionPatternEngineModuleJNI.BoolValueSwig_getNoValueMessage(swigCPtr, this);
  }

  public boolean getValue() {
    return DeviceDetectionPatternEngineModuleJNI.BoolValueSwig_getValue(swigCPtr, this);
  }

}
