/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class ConfigPatternSwig extends ConfigDeviceDetectionSwig {
  private transient long swigCPtr;

  protected ConfigPatternSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigPatternSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_ConfigPatternSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ConfigPatternSwig() {
    this(DeviceDetectionPatternEngineModuleJNI.new_ConfigPatternSwig(), true);
  }

  public void setHighPerformance() {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setHighPerformance(swigCPtr, this);
  }

  public void setBalanced() {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setBalanced(swigCPtr, this);
  }

  public void setBalancedTemp() {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setBalancedTemp(swigCPtr, this);
  }

  public void setLowMemory() {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setLowMemory(swigCPtr, this);
  }

  public void setMaxPerformance() {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setMaxPerformance(swigCPtr, this);
  }

  public void setClosestSignatures(int closestSignature) {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setClosestSignatures(swigCPtr, this, closestSignature);
  }

  public void setDifference(int difference) {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setDifference(swigCPtr, this, difference);
  }

  public void setUserAgentCacheCapacity(long capacity) {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setUserAgentCacheCapacity(swigCPtr, this, capacity);
  }

  public void setConcurrency(int concurrency) {
    DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_setConcurrency(swigCPtr, this, concurrency);
  }

  public CollectionConfigSwig getStrings() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getStrings(swigCPtr, this), true);
  }

  public CollectionConfigSwig getProperties() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getProperties(swigCPtr, this), true);
  }

  public CollectionConfigSwig getValues() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getValues(swigCPtr, this), true);
  }

  public CollectionConfigSwig getProfiles() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getProfiles(swigCPtr, this), true);
  }

  public CollectionConfigSwig getSignatures() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getSignatures(swigCPtr, this), true);
  }

  public CollectionConfigSwig getSignatureNodeOffsets() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getSignatureNodeOffsets(swigCPtr, this), true);
  }

  public CollectionConfigSwig getNodeRankedSignatureIndexes() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getNodeRankedSignatureIndexes(swigCPtr, this), true);
  }

  public CollectionConfigSwig getRankedSignatureIndexes() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getRankedSignatureIndexes(swigCPtr, this), true);
  }

  public CollectionConfigSwig getNodes() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getNodes(swigCPtr, this), true);
  }

  public CollectionConfigSwig getProfileOffsets() {
    return new CollectionConfigSwig(DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getProfileOffsets(swigCPtr, this), true);
  }

  public int getClosestSignatures() {
    return DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getClosestSignatures(swigCPtr, this);
  }

  public int getDifference() {
    return DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getDifference(swigCPtr, this);
  }

  public int getConcurrency() {
    return DeviceDetectionPatternEngineModuleJNI.ConfigPatternSwig_getConcurrency(swigCPtr, this);
  }

}
