/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class Date {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Date(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Date obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_Date(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getYear() {
    return DeviceDetectionPatternEngineModuleJNI.Date_getYear(swigCPtr, this);
  }

  public int getMonth() {
    return DeviceDetectionPatternEngineModuleJNI.Date_getMonth(swigCPtr, this);
  }

  public int getDay() {
    return DeviceDetectionPatternEngineModuleJNI.Date_getDay(swigCPtr, this);
  }

}
