/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class EnginePatternSwig extends EngineDeviceDetectionSwig {
  private transient long swigCPtr;

  protected EnginePatternSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnginePatternSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_EnginePatternSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EnginePatternSwig(String fileName, ConfigPatternSwig config, RequiredPropertiesConfigSwig properties) {
    this(DeviceDetectionPatternEngineModuleJNI.new_EnginePatternSwig__SWIG_0(fileName, ConfigPatternSwig.getCPtr(config), config, RequiredPropertiesConfigSwig.getCPtr(properties), properties), true);
  }

  public EnginePatternSwig(byte[] data, ConfigPatternSwig config, RequiredPropertiesConfigSwig properties) {
    this(DeviceDetectionPatternEngineModuleJNI.new_EnginePatternSwig__SWIG_1(data, ConfigPatternSwig.getCPtr(config), config, RequiredPropertiesConfigSwig.getCPtr(properties), properties), true);
  }

  public Date getPublishedTime() {
    return new Date(DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_getPublishedTime(swigCPtr, this), true);
  }

  public Date getUpdateAvailableTime() {
    return new Date(DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_getUpdateAvailableTime(swigCPtr, this), true);
  }

  public String getDataFilePath() {
    return DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_getDataFilePath(swigCPtr, this);
  }

  public String getDataFileTempPath() {
    return DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_getDataFileTempPath(swigCPtr, this);
  }

  public void refreshData() {
    DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_refreshData__SWIG_0(swigCPtr, this);
  }

  public void refreshData(String fileName) {
    DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_refreshData__SWIG_1(swigCPtr, this, fileName);
  }

  public void refreshData(byte[] data) {
    DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_refreshData__SWIG_2(swigCPtr, this, data);
  }

  public ResultsPatternSwig process(EvidenceDeviceDetectionSwig evidence, int closestSignatures) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_process__SWIG_0(swigCPtr, this, EvidenceDeviceDetectionSwig.getCPtr(evidence), evidence, closestSignatures);
    return (cPtr == 0) ? null : new ResultsPatternSwig(cPtr, true);
  }

  public ResultsPatternSwig process(String userAgent, int closestSignatures) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_process__SWIG_1(swigCPtr, this, userAgent, closestSignatures);
    return (cPtr == 0) ? null : new ResultsPatternSwig(cPtr, true);
  }

  public ResultsPatternSwig process(EvidenceDeviceDetectionSwig evidence) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_process__SWIG_2(swigCPtr, this, EvidenceDeviceDetectionSwig.getCPtr(evidence), evidence);
    return (cPtr == 0) ? null : new ResultsPatternSwig(cPtr, true);
  }

  public ResultsPatternSwig process(String userAgent) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_process__SWIG_3(swigCPtr, this, userAgent);
    return (cPtr == 0) ? null : new ResultsPatternSwig(cPtr, true);
  }

  public ResultsBaseSwig processBase(EvidenceBaseSwig evidence) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_processBase(swigCPtr, this, EvidenceBaseSwig.getCPtr(evidence), evidence);
    return (cPtr == 0) ? null : new ResultsBaseSwig(cPtr, true);
  }

  public ResultsDeviceDetectionSwig processDeviceDetection(EvidenceDeviceDetectionSwig evidence) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_processDeviceDetection__SWIG_0(swigCPtr, this, EvidenceDeviceDetectionSwig.getCPtr(evidence), evidence);
    return (cPtr == 0) ? null : new ResultsDeviceDetectionSwig(cPtr, true);
  }

  public ResultsDeviceDetectionSwig processDeviceDetection(String userAgent) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.EnginePatternSwig_processDeviceDetection__SWIG_1(swigCPtr, this, userAgent);
    return (cPtr == 0) ? null : new ResultsDeviceDetectionSwig(cPtr, true);
  }

}
