/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class EvidenceBaseSwig extends MapStringStringSwig {
  private transient long swigCPtr;

  protected EvidenceBaseSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionPatternEngineModuleJNI.EvidenceBaseSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EvidenceBaseSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_EvidenceBaseSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EvidenceBaseSwig() {
    this(DeviceDetectionPatternEngineModuleJNI.new_EvidenceBaseSwig(), true);
  }

  public void addFromBytes(String key, long keyLength, String value, long valueLength) {
    DeviceDetectionPatternEngineModuleJNI.EvidenceBaseSwig_addFromBytes(swigCPtr, this, key, keyLength, value, valueLength);
  }

}
