/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class ProfileMetaDataCollectionSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ProfileMetaDataCollectionSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileMetaDataCollectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_ProfileMetaDataCollectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ProfileMetaDataSwig getByKey(long key) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.ProfileMetaDataCollectionSwig_getByKey(swigCPtr, this, key);
    return (cPtr == 0) ? null : new ProfileMetaDataSwig(cPtr, true);
  }

  public ProfileMetaDataSwig getByIndex(long index) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.ProfileMetaDataCollectionSwig_getByIndex(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ProfileMetaDataSwig(cPtr, true);
  }

  public long getSize() {
    return DeviceDetectionPatternEngineModuleJNI.ProfileMetaDataCollectionSwig_getSize(swigCPtr, this);
  }

}
