/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class PropertyMetaDataSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PropertyMetaDataSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PropertyMetaDataSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_PropertyMetaDataSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getName(swigCPtr, this);
  }

  public VectorStringSwig getDataFilesWherePresent() {
    return new VectorStringSwig(DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getDataFilesWherePresent(swigCPtr, this), true);
  }

  public String getType() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getType(swigCPtr, this);
  }

  public String getCategory() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getCategory(swigCPtr, this);
  }

  public String getUrl() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getUrl(swigCPtr, this);
  }

  public boolean getAvailable() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getAvailable(swigCPtr, this);
  }

  public int getDisplayOrder() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getDisplayOrder(swigCPtr, this);
  }

  public boolean getIsMandatory() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getIsMandatory(swigCPtr, this);
  }

  public boolean getIsList() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getIsList(swigCPtr, this);
  }

  public boolean getIsObsolete() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getIsObsolete(swigCPtr, this);
  }

  public boolean getShow() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getShow(swigCPtr, this);
  }

  public boolean getShowValues() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getShowValues(swigCPtr, this);
  }

  public String getDescription() {
    return DeviceDetectionPatternEngineModuleJNI.PropertyMetaDataSwig_getDescription(swigCPtr, this);
  }

}
