/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class ResultsPatternSwig extends ResultsDeviceDetectionSwig {
  private transient long swigCPtr;

  protected ResultsPatternSwig(long cPtr, boolean cMemoryOwn) {
    super(DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultsPatternSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_ResultsPatternSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getDeviceId() {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getDeviceId__SWIG_0(swigCPtr, this);
  }

  public String getDeviceId(long resultIndex) {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getDeviceId__SWIG_1(swigCPtr, this, resultIndex);
  }

  public int getRank() {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getRank__SWIG_0(swigCPtr, this);
  }

  public int getRank(long resultIndex) {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getRank__SWIG_1(swigCPtr, this, resultIndex);
  }

  public int getDifference() {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getDifference__SWIG_0(swigCPtr, this);
  }

  public int getDifference(long resultIndex) {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getDifference__SWIG_1(swigCPtr, this, resultIndex);
  }

  public int getMethod() {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getMethod__SWIG_0(swigCPtr, this);
  }

  public int getMethod(long resultIndex) {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getMethod__SWIG_1(swigCPtr, this, resultIndex);
  }

  public int getSignaturesCompared() {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getSignaturesCompared__SWIG_0(swigCPtr, this);
  }

  public int getSignaturesCompared(long resultIndex) {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getSignaturesCompared__SWIG_1(swigCPtr, this, resultIndex);
  }

  public String getUserAgent(long resultIndex) {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getUserAgent(swigCPtr, this, resultIndex);
  }

  public int getUserAgents() {
    return DeviceDetectionPatternEngineModuleJNI.ResultsPatternSwig_getUserAgents(swigCPtr, this);
  }

}
