/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class StringValueSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringValueSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringValueSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_StringValueSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringValueSwig() {
    this(DeviceDetectionPatternEngineModuleJNI.new_StringValueSwig(), true);
  }

  public boolean hasValue() {
    return DeviceDetectionPatternEngineModuleJNI.StringValueSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return DeviceDetectionPatternEngineModuleJNI.StringValueSwig_getNoValueMessage(swigCPtr, this);
  }

  public String getValue() {
    return DeviceDetectionPatternEngineModuleJNI.StringValueSwig_getValue(swigCPtr, this);
  }

}
