/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class SWIGTYPE_p_string {
  private transient long swigCPtr;

  protected SWIGTYPE_p_string(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_string() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

