/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class ValueMetaDataCollectionSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ValueMetaDataCollectionSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValueMetaDataCollectionSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_ValueMetaDataCollectionSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValueMetaDataSwig getByKey(ValueMetaDataKeySwig key) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.ValueMetaDataCollectionSwig_getByKey(swigCPtr, this, ValueMetaDataKeySwig.getCPtr(key), key);
    return (cPtr == 0) ? null : new ValueMetaDataSwig(cPtr, true);
  }

  public ValueMetaDataSwig getByIndex(long index) {
    long cPtr = DeviceDetectionPatternEngineModuleJNI.ValueMetaDataCollectionSwig_getByIndex(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ValueMetaDataSwig(cPtr, true);
  }

  public long getSize() {
    return DeviceDetectionPatternEngineModuleJNI.ValueMetaDataCollectionSwig_getSize(swigCPtr, this);
  }

}
