/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class ValueMetaDataKeySwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ValueMetaDataKeySwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValueMetaDataKeySwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_ValueMetaDataKeySwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValueMetaDataKeySwig(String propertyName, String valueName) {
    this(DeviceDetectionPatternEngineModuleJNI.new_ValueMetaDataKeySwig(propertyName, valueName), true);
  }

  public String getPropertyName() {
    return DeviceDetectionPatternEngineModuleJNI.ValueMetaDataKeySwig_getPropertyName(swigCPtr, this);
  }

  public String getValueName() {
    return DeviceDetectionPatternEngineModuleJNI.ValueMetaDataKeySwig_getValueName(swigCPtr, this);
  }

}
