/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class VectorStringSwig extends java.util.AbstractList<String> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorStringSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStringSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_VectorStringSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorStringSwig(String[] initialElements) {
    this();
    for (String element : initialElements) {
      add(element);
    }
  }

  public VectorStringSwig(Iterable<String> initialElements) {
    this();
    for (String element : initialElements) {
      add(element);
    }
  }

  public String get(int index) {
    return doGet(index);
  }

  public String set(int index, String e) {
    return doSet(index, e);
  }

  public boolean add(String e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, String e) {
    modCount++;
    doAdd(index, e);
  }

  public String remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorStringSwig() {
    this(DeviceDetectionPatternEngineModuleJNI.new_VectorStringSwig__SWIG_0(), true);
  }

  public VectorStringSwig(VectorStringSwig other) {
    this(DeviceDetectionPatternEngineModuleJNI.new_VectorStringSwig__SWIG_1(VectorStringSwig.getCPtr(other), other), true);
  }

  public long capacity() {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_isEmpty(swigCPtr, this);
  }

  public void clear() {
    DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_clear(swigCPtr, this);
  }

  public VectorStringSwig(int count, String value) {
    this(DeviceDetectionPatternEngineModuleJNI.new_VectorStringSwig__SWIG_2(count, value), true);
  }

  private int doSize() {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doSize(swigCPtr, this);
  }

  private void doAdd(String x) {
    DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, String x) {
    DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private String doRemove(int index) {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doRemove(swigCPtr, this, index);
  }

  private String doGet(int index) {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doGet(swigCPtr, this, index);
  }

  private String doSet(int index, String val) {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    DeviceDetectionPatternEngineModuleJNI.VectorStringSwig_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
