/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fiftyone.devicedetection.pattern.engine.onpremise.interop.swig;

public class VectorStringValuesSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorStringValuesSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStringValuesSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DeviceDetectionPatternEngineModuleJNI.delete_VectorStringValuesSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorStringValuesSwig() {
    this(DeviceDetectionPatternEngineModuleJNI.new_VectorStringValuesSwig(), true);
  }

  public boolean hasValue() {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringValuesSwig_hasValue(swigCPtr, this);
  }

  public String getNoValueMessage() {
    return DeviceDetectionPatternEngineModuleJNI.VectorStringValuesSwig_getNoValueMessage(swigCPtr, this);
  }

  public VectorStringSwig getValue() {
    return new VectorStringSwig(DeviceDetectionPatternEngineModuleJNI.VectorStringValuesSwig_getValue(swigCPtr, this), true);
  }

}
