trigger: none

# Schedule to run overnight
schedules:
- cron: "0 20 * * *"
  displayName: Daily overnight build
  branches:
    include:
    - develop

resources:
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

# Include shared variables
variables:
- template: shared-variables.yml
- template: shared-variables.yml@ciTemplates
- group: CIAutomation

stages:
- template: shared-build-and-test-platforms.yml
  parameters:
    windowsImage: ${{ variables.windowsImage }}
    linuxImage: ${{ variables.linuxImage }}
    macImage: ${{ variables.macImage }}
    runTests: variables['RunTests']
    resourceRepoName: 'ciTemplates'

# Perform a security check
- template: java/shared-security-vulnerability-check.yml@ciTemplates
  parameters:
    imageName: ${{ variables.linuxImage }}
    dependencies: [Windows,Linux,MacOS]

# Try to complete the corresponding pull request if
# this is triggered by one.    
- template: shared-auto-complete-pr-stage.yml@ciTemplates
  parameters:
    stageDependencies: [SecurityCheck]