# Disable automatic runs of this pipeline when changes are pushed to the repository.
trigger: none

# Disable automatic runs of this pipeline when a PR is create.
pr: none

# Add the pipeline that builds the packages as a resource.
# This allows the deployment pipeline to be triggered whenever
# the build pipeline completes.
resources:
  pipelines:
  - pipeline: build-pipeline   # The name for the triggering build pipeline within this script
    source: device-detection-java-create-packages # Name of the pipeline
    trigger: true
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

variables:
- group: InternalKeys
# Include shared variables
- template: shared-variables.yml
- name: targetBranch
  value: 'refs/heads/master'
- group: CIAutomation
  
# Publish to internal feed  
stages:
- stage: publish_internal
  displayName: Publish Internal
  jobs:
  # Note - A 'deployment' job will automatically download the artifacts created by the triggering pipeline.
  - deployment: deploy_internal
    displayName: Deploy Internal
    pool:
      vmImage: $(linuxImage)
      workspace:
        clean: all
    environment: packages-internal
    strategy:
      runOnce:
        deploy:
          steps:
          - template: shared-publish-packages-internal.yml
            parameters:
              publishEndpoint: 'internal-feed'
              resouceKey: $(SuperResourceKey)
              internalFeedName: $(InternalFeedName)
              templates: 'ciTemplates'
          
 