# Template that runs build andn test stage on multiple platforms.

parameters:
# Provide image versions to run the job on for windows, linux and mac.
- name: windowsImage
- name: linuxImage
- name: macImage
- name: resourceRepoName
- name: runTests
  type: string
  default: 'On'

stages:
- template: data-stage.yml
  parameters:
    linuxImage: ${{ parameters.linuxImage }}
    runTests: ${{ parameters.runTests }}

- template: shared-build-and-test-stage.yml
  parameters:
    stageName: Windows
    imageName: ${{ parameters.windowsImage }}
    runTests: ${{ parameters.runTests }}
    resourceRepoName: ${{ parameters.resourceRepoName }}
    
- template: shared-build-and-test-stage.yml
  parameters:
    stageName: Linux
    imageName: ${{ parameters.linuxImage }}
    runTests: ${{ parameters.runTests }}
    resourceRepoName: ${{ parameters.resourceRepoName }}
    
- template: shared-build-and-test-stage.yml
  parameters:
    stageName: MacOS
    imageName: ${{ parameters.macImage }}
    runTests: ${{ parameters.runTests }}
    resourceRepoName: ${{ parameters.resourceRepoName }}