name: Nightly PRs to Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        description: Dry Run
        type: boolean
        default: false
      prs:
        description: PRs (comma-separated)
        type: string
  workflow_run:
    workflows: [Nightly Submodule Update]
    types: [completed]

jobs:
  # Run the common workflow on each pull request
  Nightly_PR_to_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-prs-to-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      prs: ${{ inputs.prs }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
